### ISSUE TITLE
Doesn't build in buntu : Indicate in README were does quarto come from.

### ISSUE THREAD

**Issue by dominix** [pedropark99/zig-book#1]
In Ubuntu zig-book doesn't build because quarto is missing.
can you add in README were does quarto come from  or any way to install it.
when searching for quarto in my system: I only found it in cargo but it seems it is not related.
apt #----------------------------#
En train de trier…
Recherche en texte intégral…
snap #----------------------------#
Aucun snap correspondant à "quarto"
flatpak #----------------------------#
No matches found
brew #----------------------------#
Error: No formulae or casks found for "quarto".
cargo #----------------------------#
quarto = "0.2.0"              # Your friendly Quarto game
bruto = "0.1.0"               # Artificial opponent to play the board game Quarto
courses = "0.10.0-alpha.1"    # A publishing system for interactive content

**Comment by pedropark99** [comment]
Hey @dominix ! I hope you are doing alright!

`quarto` is the CLI tool from the [Quarto Publishing System](https://quarto.org/). In order to build the book, you have to install Quarto in your machine.

You can find instrunctions on how to install in the [Get Started page](https://quarto.org/docs/get-started/)
