### ISSUE TITLE
How to export to pdf to print it

### ISSUE THREAD

**Issue by pavnguyen** [pedropark99/zig-book#26]
Hi,

I really love your book. I would like to print it in pdf. Could you export the whole book in pdf that i can print as a real book please? Thanks @pedropark99

**Comment by pedropark99** [comment]
Hello @pavnguyen ! I hope you are doing well. Unfortunately, a PDF version of the book will likely never exist. A print/physical version of the book will exist in the future when the book matures and reaches v1.0 (First edition). When we reach the first edition, the physical version of the book will be available to anyone to buy on Amazon.

So, for now, we only have this HTML/Website version of the book available. But, if I'm not mistaken, your Web Browser (Chrome, Firefox, etc.) likely have a "Print to PDF" option that you can use to print the website to a PDF. Probably this will produce some weird outputs, I mean, is a website printed to a paper, which is weird by itself. But this might be good enough for your needs.

**Comment by pedropark99** [comment]
For those who are following this issue, you can now buy an eBook or a physical version of the book on Amazon, as a way to support this project: <https://www.amazon.com/dp/B0DJYMDRLP>

**Comment by hoh** [comment]
Thanks for the great work on this book!

While it is great to offer an eBook version, Amazon does not sell ebooks but only provides a restricted license to read them on their own apps and devices only. I faced this issue since my tablet can neither read those files nor read HTML directories.

If someone else faces this issue, the source of this book can be rendered in PDF format using its standard rendering tools. Remember to [support the project](https://pedropark99.github.io/zig-book/#support-the-project).

The following `shell.nix` provides a shell environment with the required tools to test both the HTML and the PDF builds of the book.

```nix
{ pkgs ? import <nixpkgs> {} }:
let
  tex = (pkgs.texlive.combine {
   inherit (pkgs.texlive) scheme-small amsmath environ fontawesome5 orcidlink pdfcol tcolorbox tikzfill;
 });
in
pkgs.mkShell {
  buildInputs = [
    tex
    
    # Zig compiler
    pkgs.zig
    
    # R and required R packages
    pkgs.R
    pkgs.rPackages.readr
    pkgs.rPackages.knitr
    pkgs.rPackages.rmarkdown
    pkgs.rPackages.stringr
    pkgs.rPackages.gt
    pkgs.rPackages.tibble
    # For building PDF
    pkgs.rPackages.tinytex
    pkgs.librsvg
    
    # Quarto publishing system
    pkgs.quarto

    # For general development tools
    pkgs.git
  ];

  # Set environment variables for convenience
  shellHook = ''
    echo "Environment ready with Zig, R (with required packages), and Quarto."
  '';
}
```
