### ISSUE TITLE
Figure 3.1 might be incorrect

### ISSUE THREAD

**Issue by esskayesss** [pedropark99/zig-book#8]
Figure 3.1 wrongly denotes k as 32 (it should be 36)
<img width="751" alt="image" src="https://github.com/user-attachments/assets/ce9d803f-10a9-4c48-a5c6-7116a47122f0">

Also, the way you've added an entire 6-bit block of zeroes doesn't seem to be correct. Besides, 0 corresponds to 'A' and not '='.

Padding characters are added to ensure that the entire block is a multiple of 6. For this, we can 

  - add 0x padding bits "00" (if the length of the binary representation is already a multiple of 6)
  - add 1x padding bits "00" in which case, one "=" is added at the end
  - add 2x padding bits "00" in which case, the encoded data ends in "=="

there would never be a need to add more than 2 padding characters because in such a case, the bits would already fit.
<img width="870" alt="image" src="https://github.com/user-attachments/assets/f9b37e37-c78d-4167-a0e1-fd0d1c74b9bf">

Alternatively, one could also say that the output is padded in a way such that it's length is a multiple of 4. (the LCM of 6 and 8 being 24, i.e., 24/6 = 4 blocks)

**Comment by pedropark99** [comment]
Hey @esskayesss ! First of all, thank your comment! These are my thoughts:

First, you are correct when you say: "Besides, 0 corresponds to 'A' and not '=' ".

Second, I can definitely improve on the phrasing. I think you are right, I should refer to this part as a "padding", instead of an "extra block of zeros". I think it is more clear, and it also is more easy to explain to the reader.

Third, you are also right in the decimal representation part. Because this figure is currently saying that the decimal representation of the "padding" part is equal to zero... when in fact, it would be much more correct to say that the padding part is actually equal to NULL.

I will work on it 😉
